[versions]
## SDK Versions
minSdk = "21"
targetSdk = "35"
compileSdk = "35"

# Dependencies
kotlin = "2.1.0"
android-gradle-plugin = "8.8.0"

compose = "1.7.6"
composeCompiler = "1.5.15"

# Sample - Android
androidx-core = "1.15.0"
androidx-lifecycle = "2.8.7"
androidx-activity-compose = "1.10.0"
android-desugaring = "2.1.4"
koin = "4.0.0"

sharedlib = "0.1.0"

[libraries]
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }

# Sample - Android
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugaring" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

sharedlib-analytics = { module = "co.touchlab.kmmbridgespmquickstart:analytics-android-debug", version.ref = "sharedlib" }
sharedlib-breeds = { module = "co.touchlab.kmmbridgespmquickstart:breeds-android-debug", version.ref = "sharedlib" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
app-ui = [
    "compose-compiler",
    "androidx-core",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-compose",
    "compose-ui",
    "compose-tooling",
    "compose-foundation",
    "compose-material",
    "compose-activity"
]

